### ISSUE TITLE
Relative paths outside of src are not working right.

### ISSUE THREAD

**Issue by justinbmeyer** [bitovi/system-npm#15]
If I have a config with:

```js
name: "syn",
system: {
  directories: {
    lib: "src"
  }
}
```

and in a `test/foo.js`, I have:

```
import "./bar"
```

It looks in "src/test/foo.js".

**Comment by matthewp** [comment]
Added a test that confirms this bug. Looking into why it is happening now.

**Comment by matthewp** [comment]
So I think the way to fix this is to check the package we are normalizing with and make sure the parentAddress is inside the package's directories.lib folder.  It would happen here:

https://github.com/bitovi/system-npm/blob/master/npm-extension.js#L56

Agree on this approach @justinbmeyer ?

**Comment by justinbmeyer** [comment]
I think there's a better way. Will be online soon.
