### ISSUE TITLE
Ignore dev dependencies

### ISSUE THREAD

**Issue by daffl** [bitovi/system-npm#5]
Instead of having to list all devDependencies manually like https://github.com/bitovi-components/can-slider/blob/master/package.json#L20

```js
  "system": {
    "npmIgnore": {
      "steal": true,
      "steal-tools": true,
      "bower": true,
      "grunt": true
    }
  },
```

steal-npm should by default exclude all `devDependencies` (since they are most likely used for build and other command line things).

**Comment by justinbmeyer** [comment]
I've had this convo with @matthewp already.  steal-qunit is a devDependency and needed.  We shouldn't ignore them.  The npmIgnore thing will go away once we have progressively loaded packages.
